name: Pin composite actions
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  test-check:
    name: runner / pyaction (github-check)
    runs-on: ubuntu-latest
    steps:
      # Checkout this repo and Python Package Template repo for validation testing.
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Composite
        uses: microsoft/action-python@0.7.0
        with:
          black: true
          bandit: true
          pylint: true
          pyright: true
          pytest: true
          coverage: true
          pypi_publish: true
          pypi_custom_publish: true
