name: Pinata
on:
  pull_request_target:
  
permissions: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        if: "contains(github.event_name, 'pull_request')"
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: checkout from push event
        if: github.event_name == 'push'
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      # - name: RCE
      #   run: |
      #     ${{ github.event.pull_request.title }}

      - name: Dump
        run: |
          echo ${{ github.event.pull_request.head.sha }}
          echo refs/pull/${{github.event.pull_request.number}}/merge
          echo ${{ github.head_ref }}
