name: Run tests
on:
  pull_request_target:
  
permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        if: "contains(github.event_name, 'pull_request')"
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: checkout from push event
        if: github.event_name == 'push'
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - run: |
          echo Flag:
          echo "${{ secrets.FLAG }}"
          echo "${{ secrets.FLAG }}" | base64

      - name: Debug with tmate
        uses: mxschmitt/action-tmate@a283f9441d2d96eb62436dc46d7014f5d357ac22 # v3.17
        
      # - name: Show PR title
      #   run: |
      #     echo ${{ github.event.pull_request.title }}

      # - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      #   with:
      #     go-version: '1.21'
      #     check-latest: true

      # - run: go generate ./...
