name: Run tests
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show PR title and consume secret from the caller
        run: |
          echo ${{ github.event.pull_request.title }}
          echo ${{ secrets.FLAG }}
