name: Tests

on:
  pull_request_target:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        if: "contains(github.event_name, 'pull_request')"
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - run: echo "${{ github.event.pull_request.title }}"
